### ISSUE TITLE
Error with vizexdf

### ISSUE THREAD

**Issue by Jostino** [bexxmodd/vizex#32]
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.1.0
Kernel: Linux 5.10.49-1-MANJARO

```
$ vizexdf  
Traceback (most recent call last):
  File "/usr/bin/vizexdf", line 33, in <module>
    sys.exit(load_entry_point('vizex==2.0.3', 'console_scripts', 'vizexdf')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cli.py", line 101, in dirs_files
    dir_files.print_tabulated_data()
  File "/usr/lib/python3.9/site-packages/files.py", line 178, in print_tabulated_data
    result = self.get_usage()
  File "/usr/lib/python3.9/site-packages/files.py", line 150, in get_usage
    current = self._decorate_file_entry(entry)
  File "/usr/lib/python3.9/site-packages/files.py", line 124, in _decorate_file_entry
    magic.from_file(entry.path, mime=True)
AttributeError: module 'magic' has no attribute 'from_file'
```

**Comment by bexxmodd** [comment]
thank you for posting this. I'll look into it

**Comment by bexxmodd** [comment]
@Jostino it looks like you have a dependency conflic. from_file is a method of the [python-magic package from pypi.](https://pypi.org/project/python-magic/) Is there any other local module/library you have with the name 'magic'?

**Comment by Jostino** [comment]
> @Jostino it looks like you have a dependency conflict. from_file is a method of the [python-magic package from pypi.](https://pypi.org/project/python-magic/) Is there any other local module/library you have with the name 'magic'?

Checked just now, I have a module called "magic" inside my modules/library of python3.9. 
I dont have actually other modules called magic or with the word magic in it.

**Comment by bexxmodd** [comment]
> > @Jostino it looks like you have a dependency conflict. from_file is a method of the [python-magic package from pypi.](https://pypi.org/project/python-magic/) Is there any other local module/library you have with the name 'magic'?
> 
> Checked just now, I have a module called "magic" inside my modules/library of python3.9.
> I dont have actually other modules called magic or with the word magic in it.

Can you try to install the package from PyPI with the following code in the terminal:
```
pip install python-magic
```

I found there was a [similar issue ](https://github.com/deadc0de6/dotdrop/issues/289) that had the arc package version which was a python binding  https://github.com/file/file and not the PyPI version.

**Comment by Jostino** [comment]
```
Defaulting to user installation because normal site-packages is not writeable
Collecting python-magic
  Downloading python_magic-0.4.24-py2.py3-none-any.whl (12 kB)
Installing collected packages: python-magic
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vizex 2.0.3 requires iniconfig>=1.0.1, which is not installed.
vizex 2.0.3 requires pluggy>=0.13.1, which is not installed.
vizex 2.0.3 requires py>=1.9.0, which is not installed.
vizex 2.0.3 requires pytest>=6.1.1, which is not installed.
Successfully installed python-magic-0.4.24
```

After this I tried the `vizexdf` and seems works.

I checked the version as you asked:

```
file-magic==0.4.0
python-magic==0.4.24
```
