### ISSUE TITLE
No matching distribution found for vizex

### ISSUE THREAD

**Issue by albertsilliker** [bexxmodd/vizex#33]
After following install procedure, pip install vizex shows the message.:  
Could not find a version that satisfies the requirement vizex (from versions: )
No matching distribution found for vizex

**Comment by bexxmodd** [comment]
Do you have `pip` installed on your machine?
Can you please run the following command in the terminal and copy the output in the comment?
```
pip install vizex
```

**Comment by bexxmodd** [comment]
I assume issue was resolved?
