### ISSUE TITLE
Namespaces are one honking great idea -- let's do more of those!

### ISSUE THREAD

**Issue by diefans** [bexxmodd/vizex#34]
IMHO I just want to point out, that your project does not use any kind of namespace, e.g. 
```
py_modules=['cli', 'disks', 'tools', 'charts', 'battery', 'cpu', 'files', 'viztree']
```
The point is, that this together with other similar projects can/will (Murphy's law?) mess up your env...
So a sane/common way would be to have a parent package typically called like the pypi project itself (`vizex`).

...I stumbled upon this while reading your blog and since your are studying computer science, it could be worth telling you... feel free to ignore/close this issue...

**Comment by bexxmodd** [comment]
@diefans it's a great observation and thanks for raising the issue!

I've been thinking to repackage and give a better organization to the code and will add namespaces.

**Comment by bexxmodd** [comment]
the project has been split it submodules to prevent naming conflicts
