### ISSUE TITLE
Vizextree not available as standalone utility

### ISSUE THREAD

**Issue by linuxlala** [bexxmodd/vizex#36]
I've tried the 2.0.3 version as well as the Master branch. Even though the project mentions that the vizex --tree function has been moved to a standalone vizextree command, it's not available in the default installation.

Am I missing something?

**Comment by bexxmodd** [comment]
Thanks for reporting this! 
it looks like the entry point for the vizextree was not registered. I updated and pushed the change to the PyPi as a version 2.0.5

you can update your vizexs version with `pip install --upgrade vizex` and after that `vizextree` should work

**Comment by linuxlala** [comment]
I can confirm that the upgrade to v2.0.5 resolved this issue. Thanks for the quick turnaround!
