### ISSUE TITLE
CPU speed units incorrect (should be MHz or GHz not hz)

### ISSUE THREAD

**Issue by chrisbeardy** [bexxmodd/vizex#42]
![image](https://user-images.githubusercontent.com/20585410/152196837-aa3ceb1a-d1a5-42b3-ae84-cc7efbef99f5.png)

Hello, 

The unit display for me is wrong for the CPU speeds. e.g. for current it should show 3.7GHz or 3700MHz, for min it should show 0.8GHz or 800MHz and max should be 5700MHz..

**Comment by bexxmodd** [comment]
Thanks, Chris for reporting this. This module is at very early stage, which I merged with main branch by accident
